version: '3.8'

services:
  web:
    build: ./
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/data_voice/static
      - media_volume:/data_voice/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine3.22
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/data_voice/static
      - media_volume:/data_voice/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: