version: '3.8'

services:
  web:
    build: ./
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/data_voice/static
      - media_volume:/data_voice/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine3.22
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/data_voice/static
      - media_volume:/data_voice/media
    ports:
      - 80:80
    depends_on:
      - web

  limesurvey:
    image: acspri/limesurvey
    container_name: limesurvey
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./limesurvey/plugins:/var/www/html/plugins
      - ./limesurvey/upload:/var/www/html/upload
      - ./limesurvey/config:/var/www/html/application/config


  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ya.1384.1214
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env.dev


volumes:
  postgres_data:
  static_volume:
  media_volume:
  mysql_data: