# Generated by Django 4.2 on 2025-04-15 16:01

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
