# Generated by Django 4.2 on 2025-04-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='report',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='report.report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.ForeignKey(default=44456, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='report.report'),
            preserve_default=False,
        ),
    ]
