# Generated by Django 4.2 on 2025-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='report',
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default=68988),
            preserve_default=False,
        ),
    ]
