# Generated by Django 4.2 on 2025-04-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_report_answer_remove_report_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default=68498),
            preserve_default=False,
        ),
    ]
