# Generated by Django 4.2 on 2025-04-15 16:40

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_time',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_time',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
