# Generated by Django 4.2 on 2025-04-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_answer_question_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
