# Generated by Django 4.2 on 2025-04-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
