# Generated by Django 4.2 on 2025-04-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='id',
            new_name='sid',
        ),
    ]
