# Generated by Django 4.2 on 2025-04-15 15:59

import apps.voice_process.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=apps.voice_process.models.Voice.folder_picture_name)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_report', to='report.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
