# Generated by Django 4.2 on 2025-04-20 11:10

import apps.voice_process.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=apps.voice_process.models.Voice.folder_picture_name)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_response', to='report.response')),
            ],
        ),
    ]
